# Generated by Django 4.2 on 2023-04-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('imei', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Standby', 'Standby'), ('Malfunctioned', 'Malfunctioned'), ('Deployed', 'Deployed')], default='Standby', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('product_model', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Standby', 'Standby'), ('Malfunctioned', 'Malfunctioned'), ('Deployed', 'Deployed')], default='Standby', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm', models.FloatField(null=True)),
                ('gaseous', models.CharField(max_length=255, null=True)),
                ('meteorological', models.CharField(max_length=255, null=True)),
                ('other_pollutants', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('p_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.pollutionsensor')),
            ],
        ),
        migrations.CreateModel(
            name='GPSOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('gps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.gpsdevice')),
                ('plate_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GPSCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('speed', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('gpsdevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.gpsdevice')),
            ],
        ),
    ]
