# Generated by Django 4.1.3 on 2022-11-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('location_longtitude', models.CharField(max_length=255)),
                ('location_latitude', models.CharField(max_length=255)),
                ('location_elevation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.CharField(max_length=255)),
                ('time_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('road_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_count', models.CharField(max_length=255)),
                ('vehicle_velocity', models.CharField(max_length=255)),
            ],
        ),
    ]
