# Generated by Django 4.1.3 on 2022-11-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0002_location_records_road_vehicles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
