# Generated by Django 4.1.3 on 2022-11-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0003_rename_records_record_rename_vehicles_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='road_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.road'),
        ),
    ]
