# Generated by Django 4.1.3 on 2022-11-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0004_record_road_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='road_type',
            new_name='road',
        ),
    ]
