# Generated by Django 4.1.3 on 2022-11-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0005_rename_road_type_record_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.location'),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.vehicle'),
        ),
    ]
