# Generated by Django 4.1.3 on 2023-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0006_record_location_record_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=255, null=True),
        ),
    ]
