# Generated by Django 4.1.3 on 2023-04-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0007_alter_record_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('IMEI_number', models.CharField(max_length=255, null=True)),
                ('product_model', models.CharField(max_length=255, null=True)),
                ('network', models.CharField(max_length=255, null=True)),
                ('SIM_number', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPSInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('speed', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gpsdevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.gpsdevice')),
            ],
        ),
    ]
