# Generated by Django 4.1.3 on 2023-04-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0009_gpsdevice_main_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('product_model', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPSHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_operator', models.CharField(max_length=255, null=True)),
                ('vehicle_plate', models.CharField(max_length=255, null=True)),
                ('operator_contact', models.CharField(max_length=255, null=True)),
                ('gpsdevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.gpsdevice')),
            ],
        ),
        migrations.CreateModel(
            name='AirPollutionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm', models.FloatField(null=True)),
                ('gaseous', models.CharField(max_length=255, null=True)),
                ('meteorological', models.CharField(max_length=255, null=True)),
                ('other_pollutants', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pollution_detector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.pollutiondetector')),
            ],
        ),
    ]
