# Generated by Django 4.1.3 on 2023-04-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0010_pollutiondetector_gpsholder_airpollutioninformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=255, null=True)),
                ('make', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gpsholder',
            old_name='operator_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='gpsholder',
            old_name='vehicle_operator',
            new_name='operator',
        ),
        migrations.RemoveField(
            model_name='gpsholder',
            name='vehicle_plate',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_elevation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_longtitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='gpsholder',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmsapp.gpsvehicle'),
        ),
    ]
