# Generated by Django 4.1.3 on 2023-04-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0011_gpsvehicle_rename_operator_contact_gpsholder_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
