# Generated by Django 4.1.3 on 2023-04-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0012_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='status',
            field=models.CharField(choices=[('S', 'Standby'), ('R', 'Reparing'), ('M', 'Malfunctioned'), ('D', 'Deployed')], default='S', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollutiondetector',
            name='status',
            field=models.CharField(choices=[('S', 'Standby'), ('R', 'Reparing'), ('M', 'Malfunctioned'), ('D', 'Deployed')], default='S', max_length=255, null=True),
        ),
    ]
