# Generated by Django 4.1.3 on 2023-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmsapp', '0014_alter_gpsdevice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdevice',
            name='status',
            field=models.CharField(choices=[('Standby', 'Standby'), ('Reparing', 'Reparing'), ('Malfunctioned', 'Malfunctioned'), ('Deployed', 'Deployed')], default='Standby', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollutiondetector',
            name='status',
            field=models.CharField(choices=[('Standby', 'Standby'), ('Reparing', 'Reparing'), ('Malfunctioned', 'Malfunctioned'), ('Deployed', 'Deployed')], default='Standby', max_length=255, null=True),
        ),
    ]
